### ISSUE TITLE
About volumes

### ISSUE THREAD

**Issue by CWempe** [wHyEt/Awtrix2-Docker#3]
First of all: I am no docker expert either. 😄 

But I am not sure if the volumes are defned correctly in the current Dockerfile.

1.
At the moment there is a generic volume created each time I execute `docker run ...`.
So after a few tim `/var/lib/docker/voilumes/` contains some folders like `29f22151dc4478b268....` wich each contains `/containerdata/docker-entrypoint.sh`.

Maybe this can be replaces by the `CMD`command instead of the `docker-entrypoint.sh` script.
Or we should point out in the README that the user should define a named volume for this.
I am not sure.

2.
But the `/data` folder should be defined as a volume in the Dockerfile, I think..

**Comment by wHyEt** [comment]
Well im no docker expert either so learning something new is always my goal ;)
1.
The generic volume is wanted because the docker-entrypoint.sh is created dynamically on the build of the container. Otherwise the entrypoint file can't be found on the start. 
2.
Like in the Readme said if you want persistent data add -v pwd:/data ;)
